**NUMPY**

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4]) # liste görevi gören ama tektip bilgi işleyen numpy arrayi

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14,5,6,7,2]) # gördüğümüz gibi tek tip float yapıyor

array([3.14, 5.  , 6.  , 7.  , 2.  ])

In [6]:
np.array([3.14,5,6,7], dtype = int) # dtype yazarak tek tipi belirleyebiliriz.

array([3, 5, 6, 7])

**SIFIRDAN ARRAY OLUŞTURMA**

In [7]:
np.zeros(10,dtype = int) # tek boyutlu 10 tane 0 fonksiyonu

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5),dtype = int) # 3 e 5 lik 1 fonksiyonu 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((3,5),4) # 3,5 lik 3 fonksiyonu full

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [10]:
np.arange(0,31,4) # 0,31 arası 4 er artan fonksiyon

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [11]:
np.linspace(0,1,11) # 0,1 arası 11 tane sayı eşit aralıklı

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.random.normal(10,4,(3,4)) # ortalama 10, standart sapma 4, 3 e 4 lük matris

array([[ 8.4064399 ,  8.45611271,  7.20175898,  7.54740386],
       [11.71556087,  8.10790608,  6.06900119, 10.25526326],
       [16.22530276,  6.57473056,  7.94288135, 11.73575823]])

In [13]:
np.random.randint(0,10,(3,3))   # 0 10 arası random 3 e 3 lük matris

array([[1, 1, 9],
       [3, 0, 5],
       [7, 3, 8]])

**Numpy Array Özellikleri**

In [14]:
c = np.random.randint(0,10, (3,4))
c

array([[2, 4, 3, 1],
       [3, 3, 4, 1],
       [3, 2, 9, 9]])

In [15]:
c.ndim     #boyutu

2

In [16]:
c.shape    # kaça kaçlık

(3, 4)

In [17]:
c.size     #eleman sayısı

12

In [18]:
c.dtype    #elemanların türü

dtype('int32')

**Yeniden Şekillendirme (reshaping)**

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10).reshape((3,3)) # 3,3 e dönüştürdük

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a.ndim

1

In [23]:
a.reshape((3,3))       # 3e3 lük 2 boyutlu bir matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a.ndim

1

In [25]:
b = a.reshape((3,3))      #şimdi değişti boyut

In [26]:
b.ndim

2

**Array Birleştirme (concatenation)**

In [27]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [28]:
np.concatenate([x,y]) #birleştirmek

array([1, 2, 3, 4, 5, 6])

In [29]:
z = np.array([7,8,9])

In [30]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# iki boyut için

In [32]:
a = np.array([[1,2,3],         # iki tane köşeli parantez iki boyut
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate([a,a], axis = 0) #sütun bazında birleşti

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
np.concatenate([a,a], axis = 1) # satır bazında birleşti

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Array Ayırma (splitting)** 

In [37]:
x = np.array([1,2,3,99,99,3,2,1])

In [42]:
np.split(x, [3,5]) # 3.ye kadar ayır sonra 5.ye kadar ayır dedik

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [43]:
a,b,c = np.split(x, [3,5])
print(a,b,c)

[1 2 3] [99 99] [3 2 1]


In [ ]:
# iki boyutlu ayırma

In [54]:
m = np.arange(16).reshape(4,4) # örnek array
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.vsplit(m, [2]) # Vertical , dikey ayırma

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [62]:
ust,alt = np.vsplit(m, [2])

In [63]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.hsplit(m,[2]) # Horizontal , yatay ayırma

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [71]:
sag , sol = np.hsplit(m,[2])

In [72]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [73]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Sıralama (sorting)**

In [74]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [75]:
np.sort(v) #sıraladık

array([1, 2, 3, 4, 5])

In [76]:
# iki boyutlu sıralama

In [80]:
m = np.random.normal(20,5,(3,3)) # ortalama 20,s.sapma 5 olan 3 e 3 lük örnek array
m

array([[28.95920657, 14.1879075 , 25.72563951],
       [15.07572244, 13.04480969, 17.67633688],
       [17.52985259, 23.83888246, 16.98538677]])

In [81]:
np.sort(m, axis = 0) # sütunlara göre sıraladık 

array([[15.07572244, 13.04480969, 16.98538677],
       [17.52985259, 14.1879075 , 17.67633688],
       [28.95920657, 23.83888246, 25.72563951]])

In [82]:
np.sort(m, axis = 1) # satırlara göre sıraladık

array([[14.1879075 , 25.72563951, 28.95920657],
       [13.04480969, 15.07572244, 17.67633688],
       [16.98538677, 17.52985259, 23.83888246]])

**İndex ile Elemanlara Erişmek**

In [101]:
a = np.random.randint(0,10, size = 10)
a

array([6, 9, 8, 4, 1, 5, 5, 6, 9, 1])

In [102]:
a[0]

6

In [103]:
a[-2]

9

In [104]:
a[0] = 31
a

array([31,  9,  8,  4,  1,  5,  5,  6,  9,  1])

In [105]:
# iki boyutta 

In [106]:
a = np.random.randint(0,10, size = (3,5))
a

array([[5, 3, 1, 3, 4],
       [7, 3, 4, 1, 0],
       [9, 8, 5, 6, 0]])

In [107]:
a[1,1]

3

In [108]:
a[1,4]

0

In [109]:
a[1,4] = 31
a

array([[ 5,  3,  1,  3,  4],
       [ 7,  3,  4,  1, 31],
       [ 9,  8,  5,  6,  0]])

**Alt kümelere erişmek(slicing ile)**

In [110]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [111]:
a[:3]

array([20, 21, 22])

In [112]:
a[1::2] # 1.index dahil 2şer 2şer ilerle

array([21, 23, 25, 27, 29])

In [113]:
# iki boyutlu slice işlemleri

In [114]:
m = np.random.randint(10, size = (5,5))
m

array([[3, 4, 4, 7, 9],
       [3, 8, 8, 3, 6],
       [3, 6, 9, 0, 8],
       [6, 3, 9, 3, 0],
       [7, 8, 7, 2, 3]])

In [115]:
m[:,0] # bütün satırları seç içinden sütunu 0.yı getir

array([3, 3, 3, 6, 7])

In [116]:
m[2,:] # bütün sütunları seç içinden 2.satırı getir

array([3, 6, 9, 0, 8])

In [117]:
m[0:2,0:2] # 0,2 satır, 0,2 sütun al

array([[3, 4],
       [3, 8]])

In [118]:
m[:,:2] # tüm satırları al 0,2 arası sütun al

array([[3, 4],
       [3, 8],
       [3, 6],
       [6, 3],
       [7, 8]])

**Alt küme üzerinde işlem yapmak**

In [ ]:
a = np.random.randint(10, size = (5,5))
a

In [ ]:
alt_a = a[0:3 , 0:3]
alt_a

In [ ]:
alt_a[0,0] = 999

In [ ]:
alt_a

In [ ]:
a

In [ ]:
# gördüğümüz gibi alt kümede yaptığımız değişiklik ana matrisi etkiledi 
# bunu engellemek için copy fonksiyonunu kullanıyoruz


In [ ]:
b = np.random.randint(10, size = (5,5))
b

In [ ]:
alt_b = b[0:3,0:2].copy()
alt_b

In [ ]:
alt_b[0,0] = 31

In [ ]:
alt_b

In [ ]:
b

In [ ]:
# gördüğümüz gibi ana matrisi eklemedi.

**Fancy index ile elemanlara erişmek**

In [ ]:
v = np.arange(0,30,3)
v

In [ ]:
[v[1],v[3],v[5]]

In [ ]:
#fancy index ile 

In [ ]:
al_getir = [1,3,5]

In [ ]:
v[al_getir]

In [ ]:
# işte bu fancy indextir

In [ ]:
#iki boyutta fancy

In [ ]:
m = np.arange(9).reshape(3,3)
m

In [ ]:
satirdanal = np.array([0,1])
sutundanal = np.array([1,2])

In [ ]:
m[satirdanal , sutundanal]

In [ ]:
#basit index ile fancy index

In [ ]:
m

In [ ]:
m[0,[1,2]]

In [ ]:
#slice ile fancy index

In [ ]:
m[0:,[1,2]]

**Koşullu eleman işlemleri**

In [ ]:
v = np.array([1,2,3,4,5])
v

In [ ]:
v <= 3 #şart sağlanıyor mu kontrol ettik

In [ ]:
v[v <= 3] #şartı sağlayanları arrayleştirdik

In [ ]:
v[v == 3]

In [ ]:
v[v != 3] # 3 olmayanlar

In [ ]:
v

In [ ]:
v**2

**Matematiksel İşlemler**

In [ ]:
v = np.array([1,2,3,4,5])

In [ ]:
# ufunc mekanizması çalışır işlemlerde

In [ ]:
eksi = np.subtract(v,1)
arti = np.add(v,2)
carpi = np.multiply(v,4)
bolu = np.divide(v,2)
us = np.power(v,2)
kalan = np.mod(v,2)
mutlak = np.absolute(v)
log = np.log10(v)

In [ ]:
np.array([eksi,arti,carpi,bolu,us,kalan,mutlak,log])

In [ ]:
# islemleri bilmiyorsak ?np veya numpy mathematics cheat sheet diye arat google'da

**Deklem Çözmek**

5 * x0 + x1 = 12
x0 + 3 * x1 = 10

In [ ]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [ ]:
a

In [ ]:
b

In [ ]:
x = np.linalg.solve(a,b)
x

**Pandas Serisi Oluşturmak**

In [ ]:
# numpy serilerine ek olarak tip bilgisi de tutulur. dolayısıyla tek tip değildir.

In [ ]:
import pandas as pd

In [ ]:
pd.Series([10,88,3,4,5])

In [ ]:
seri = pd.Series([10,88,3,4,5])

In [ ]:
type(seri) #seri tipi

In [ ]:
seri.dtype #değişken tipi

In [ ]:
 seri.axes #nerde başladı nerde bitti

In [ ]:
seri.size #büyüklüğü

In [ ]:
seri.ndim #boyutu

In [ ]:
seri.values # array şeklinde yazmak

In [ ]:
seri.head(3) #ilk 3 tanesi

In [ ]:
seri.tail(3) #sondan 3 tanesi

In [ ]:
#index isimlendirme

In [ ]:
pd.Series([99,22,332,94,5])

In [ ]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"]) #indexleri biz belirledik

In [ ]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [ ]:
seri["a"] # a indexi neye karşılık geliyor

In [ ]:
seri["a":"c"] # a,dan c ye kadar al , c dahil !!!!

In [ ]:
# sözlük üzerinden liste oluşturmak

In [ ]:
sozluk = pd.Series({"reg":10, "log":11, "cart":12}) # dictionary olarak belirledik seriyi
sozluk

In [ ]:
# iki seriyi birleştirerek seri oluşturma

In [ ]:
pd.concat([seri,seri]) # iki seriyi toplama, alt alta olur

**Eleman İşlemleri**

In [ ]:
a = np.array([1,2,33,444,75])

In [ ]:
seri = pd.Series(a) # numpy listesini pandas serisine dönüştürebiliriz

In [ ]:
seri

In [ ]:
seri[0]

In [ ]:
seri[1:3] 

In [ ]:
seri = pd.Series([123,345,124,656], index = ["reg","log","cart","rf"])
seri # karşımıza böyle çıkar genelde.

In [ ]:
seri.index # indexleri verir

In [ ]:
seri.keys #  keysleri verir

In [ ]:
list(seri.items())    ayrı ayrı index ve keyleri görüntüledik

In [ ]:
seri.values # array formunda yazdık

In [ ]:
#eleman sorgulama

In [ ]:
"reg" in seri # içinde mi sorgulama

In [ ]:
#fancy eleman

In [ ]:
seri[["rf","reg"]] # rf ve reg değerlerini getir dedik

In [ ]:
seri["reg"] = 13 # regi 13 belirledik

In [ ]:
seri

In [ ]:
seri["reg":"log"] # reg log arası çıkar dedik

**Pandas DataFrame Oluşturma**

In [ ]:
l = [1,2,39,67,90]

In [ ]:
pd.DataFrame(l, columns = ["namevalues"]) #sütun ismi belirledik

In [ ]:
m = np.arange(1,10).reshape((3,3))
m

In [ ]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

In [ ]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"]) 

In [ ]:
df.columns = ("deg1","deg2","deg3") #sütun ismi değiştirme kısayolu
df

In [ ]:
type(df) 

In [ ]:
df.axes #index,keys bilgisi verdi

In [ ]:
df.shape [boyut sayısı]

In [ ]:
df.ndim [boyutu]

In [ ]:
df.size [büyüklüğü kaç eleman var]

In [ ]:
df.values # numpy arrayi şeklinde yazdı

In [ ]:
type(df.values)

In [ ]:
df.head(1) #baştan ilk satırı yazdı

In [ ]:
df.tail(1) #sondan ilk satırı yazdı

In [ ]:
a = np.array([1,2,3,4,5]) 

In [ ]:
pd.DataFrame(a, columns = ["deg1"]) #arrayi dataframe yapıp sütunu isimlendirdik

**Pandas DataFrame Eleman İşlemleri**

In [ ]:
s1 = np.random.randint(10,size = 5)  
s2 = np.random.randint(10,size = 5) 
s3 = np.random.randint(10,size = 5) 

In [ ]:
sozluk = {"var1":s1,"var2":s2,"var3":s3}
sozluk

In [ ]:
df = pd.DataFrame(sozluk)

In [ ]:
df

In [ ]:
df[0:1]

In [ ]:
df.index

In [ ]:
df.index = ["a","b","c","d","e"] 
df

In [ ]:
df.index

In [ ]:
df["c":"e"]

In [ ]:
df.drop("a",axis = 0) #anlık silme işlemi. axis ile satırı sil dedik

In [ ]:
df #gördüğümüz gibi silinmedi

In [ ]:
df.drop("a",axis = 0,inplace = True) #kalıcı uçurma

In [ ]:
df

In [ ]:
# fancy ile toplu silme

In [ ]:
liste = ["b","c","d"]

In [ ]:
df.drop(liste, axis = 0)

In [ ]:
"var1" in df

In [ ]:
l = ["var1","var2","var4"]

In [ ]:
for i in l:
    print(i in df)
    

In [ ]:
df

In [ ]:
df["var4"] = df["var1"] * df["var2"]

In [ ]:
df

In [ ]:
df.drop("var4", axis = 1,inplace = True)
df

In [ ]:
lk = ["var3"]

In [ ]:
df.drop(lk, axis = 1)

**Gözlem ve Değişken Seçimi**

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
m = np.random.randint(1,30,size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

In [ ]:
#loc : sondaki dahil,serbest

In [ ]:
df.loc[0:3]

In [ ]:
# iloc: sondaki dahil değil,kurallara bağlı

In [ ]:
df.iloc[0:3]

In [ ]:
df.iloc[:3,:2]

In [ ]:
df.loc[0:3,"var3"]

In [ ]:
df.iloc[0:4] ["var3"]

**Koşullu Eleman İşlemleri**

In [ ]:
m = np.random.randint(1,30,size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

In [ ]:
df["var1"] # 1.sütunu seç

In [ ]:
df["var1"][0:2] #1.sütunda 2ye kadar olan satırları getir

In [ ]:
df[0:2][["var1","var2"]] #2 ye kadar olan satırları sadece var 1 ve var 2 için getir

In [ ]:
df

In [ ]:
df.var1 #df["var1"] ile aynı şey

In [ ]:
df[df.var1 > 15] # var1 sütununda 15ten büyük olanları al ama diğer sütunlarda gözükür

In [ ]:
df[df.var1 > 15][["var1"]] # var 1 sütunu 15ten büyük sadece var 1i al

In [ ]:
df[(df.var1 > 15) & (df.var2 < 10)] #ikili koşul bu

In [ ]:
df[df.var1 > 15][["var1","var2"]] # var 1 ve var 2 yi getir ama var 1 15ten büyük olsun

**Birleştirme İşlemleri (Join)**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
m = np.random.randint(1,30, size = (5,3))

In [ ]:
df1 = pd.DataFrame(m,columns = ["var1","var2","var3"])
df1

In [ ]:
df2 = df1 + 10
df2

In [ ]:
pd.concat([df1,df2])

In [ ]:
pd.concat([df1,df2], ignore_index = True) #yukarda indexler 0123401234 şeklndeydi düzelttik

In [ ]:
df1.columns

In [ ]:
df2.columns

In [ ]:
df2.columns = ["var1","var2","deg3"]

In [ ]:
df2

In [ ]:
pd.concat([df1,df2]) #sütunlar farklı olunca hata verdi

In [ ]:
pd.concat([df1,df2], axis = 0 ,join = "inner") # sadece kesişen sütunlar alındı

**İleri Birleştirme İşlemleri**

In [ ]:
#birebir birleştirme

In [ ]:
df1 = pd.DataFrame({"calisanlar" : ['Ali','Veli','Ayse','Fatma'], "sektor" : ["muhasebe","muhendislik","e_muhendislik","ik"]})
df1

In [ ]:
df2 = pd.DataFrame({"calisanlar" : ["Ali","Veli","Ayse","Fatma"], "girisyil" : ["2010","2009","2014","2019"]})
df2

In [ ]:
pd.merge(df1,df2) #merge fonksiyonu birebir birleştirdi.

In [ ]:
#coktan teke

In [ ]:
df3 = pd.merge(df1,df2)
df3

In [ ]:
df4 = pd.DataFrame({"sektor": ["muhasebe","muhendislik","ik"], "mudur" : ["Caner","Mustafa","Berkcan"]})
df4

In [ ]:
pd.merge(df3,df4)

In [ ]:
# coktan coka

In [ ]:
df5 = pd.DataFrame({"sektor": ["muhasebe","muhasebe","muhendislik","muhendislik","ik","ik"],
                    "yetenekler": ["matematik","excel","kodlama","linux","excel","yonetim"]})
df5

In [ ]:
df1

In [ ]:
pd.merge(df1,df5) # calisanlar çokladı

**Toplulaştırma(Aggregation)**

basit toplulaştırma fonksiyonları
* count() kaç tane 
* first() ilk değer
* last() son değer
* mean() ortalama
* median() medyan 
* min() min değer
* max() max değer 
* std() standart sapması
* var() varyans
* sum() toplam

In [ ]:
import seaborn as sns  # veri setleri var bu kütüphanede

In [ ]:
df = sns.load_dataset("planets")
df.head()

In [ ]:
df.shape

In [ ]:
df.mean() 

In [ ]:
df["mass"].mean()

In [ ]:
df["mass"].count()

In [ ]:
df["mass"].min()

In [ ]:
df["mass"].max()

In [ ]:
df["mass"].sum()

In [ ]:
df["mass"].std()

In [ ]:
df["mass"].var()

In [ ]:
df.describe().T # describe() fonksiyonu tüm bu istatistikler hesaplarn olduğu fonk.dur
                # ayrıca .T ise transpozedir,değişkenleri yer değiştirir.

In [ ]:
df.dropna().describe().T # dropna() eksik değerleri silerek hesapladı

**Gruplama(Grouping)**

In [ ]:
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"], "veri": [10,11,52,23,43,55]},columns = ["gruplar","veri"])
df

In [ ]:
df.groupby("gruplar") #grupları yakaladık

In [ ]:
df.groupby("gruplar").mean()

In [ ]:
df = sns.load_dataset("planets")

In [ ]:
df.head()

In [ ]:
df.groupby("method")

In [ ]:
df.groupby("method")["orbital_period"].mean() 
#benzer methodları listeledi ve onların ortalamasını verdi.

In [ ]:
df.groupby("method")["orbital_period"].describe()

**İleri Toplulaştırma İşlemleri(Aggregate,filter,transform,apply)**

In [ ]:
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"],
                  "degisken1" : [10,23,33,22,11,99],
                   "degisken2" : [100,253,333,262,111,969]},
                   columns = ["gruplar","degisken1","degisken2"])
df

**Aggregate(Toplulaştırma)** 

In [ ]:
df.groupby("gruplar")

In [ ]:
df.groupby("gruplar").aggregate([min,np.median,max]) #aggregate kendi seçtiğimiz fonksiyonları verir 
                                                    #burada np.median dışardan geliyor.tırnak içinde yazılamaz.

In [ ]:
df.groupby("gruplar").aggregate({"degisken1": [min],"degisken2": [max]}) #degiskenler için farklı işlem
                                                                        #sözlük!

**Filter** (Filtreleme)

In [ ]:
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"],
                  "degisken1" : [10,23,33,22,11,99],
                   "degisken2" : [100,253,333,262,111,969]},
                   columns = ["gruplar","degisken1","degisken2"])
df

In [ ]:
def filter_func(x):                    #pandasın verdiği fonksiyon harici özel karışık,fonksiyon tanımladık
    return x["degisken1"].std() > 9

In [ ]:
df.groupby("gruplar").std()

In [ ]:
df.groupby("gruplar").filter(filter_func) # bu fonksiyon ile filtreledik sonuçları

**Transform (Değişkenler üzerinde dönüştürme)**

In [ ]:
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"],
                  "degisken1" : [10,23,33,22,11,99],
                   "degisken2" : [100,253,333,262,111,969]},
                   columns = ["gruplar","degisken1","degisken2"])
df

In [ ]:
df["degisken1"]*9 # değişken 1 i 9 la çarptık. peki daha karmaşıksa?

In [ ]:
df_a = df.iloc[:,1:3] # iloc yardımı ile harf içeren gruplar değişkenini kapadık
df_a

In [ ]:
df_a.transform(lambda x: (x - x.mean()) / x.std()) #transform() fonksiyonu ilgili frame'in tüm değişkenlerini senin istediğin şekilde değiştirir.
                                                    #içine lambda fonksiyonu yazdık ve lamdanın ne yapmamızı istediğini kararlaştırdık.

**Apply**

In [ ]:
df = pd.DataFrame({"degisken1" : [10,23,33,22,11,99],
                   "degisken2" : [100,253,333,262,111,969]},
                   columns = ["degisken1","degisken2"])
df

In [ ]:
df.apply(np.sum)

In [ ]:
df.apply(lambda x: x-3)

**Pivot İşlemler**

In [ ]:
import seaborn as sns 

In [ ]:
titanic = sns.load_dataset("titanic")
titanic.head()

In [ ]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

In [ ]:
titanic.pivot_table("survived",index =  "sex", columns = "class")

In [ ]:
titanic.age.head()

In [ ]:
age = pd.cut(titanic["age"], [0, 18 , 90])

In [ ]:
titanic.pivot_table("survived", index = ["sex",age] , columns = "class")

**Dış Kaynaklı Veri Okuma**

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import seaborn as sns

In [ ]:
#csv okuma

In [ ]:
pd.read_csv("readingdata/ornekcsv.csv", sep = ";")

In [ ]:
#txt okuma

In [ ]:
pd.read_csv("readingdata/duz_metin.txt")

In [ ]:
#excell okuma

In [ ]:
pd.read_excel("readingdata/ornekx.xlsx")

**Problem Çözme ve Döküman Okuma Kültürü**

In [ ]:
#stackoverflow.com    PROBLEM SİTESİ

In [ ]:
#kütüphanelerin dökümentasyonunu incele

In [ ]:
#cheat sheet arayabilirsin.